### ISSUE TITLE
Nokia lumia 625

### ISSUE THREAD

**Issue by yusufkaya06** [ceyhunkeklik/ApkInstallerForWindows10Mobile#1]
Nokia lumia 625 telefonda çalışmıyor uygulama ne yapmak lazım desteklemesi için.

**Comment by ceyhunkeklik** [comment]
Açıklamada da belirttiğim gibi, Microsoft Android projesini iptal ettiğinden dolayı hiçbir Windows telefon için hiçbir yöntemle apk yüklemek mümkün değildir.

"This application is not working now. Because Microsoft disabled Project Astoria for mobile."
